baseURL = 'https://fancive.github.io/'
languageCode = "en-us"
DefaultContentLanguage = "en"
disqusShortname = "fancive-github-com"
title = ''
theme = "ananke"
publishDir = "docs"
preserveTaxonomyNames = true
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-7N49ZFJ61J"


[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"


[languages]
    [languages.en]
        weight = 1
        title = "fancivez"

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"


[menu]
    [[menu.main]]
        identifier = "categories"
        name = "categories"
        url = "/categories/"
        weight = 10
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = 10
    [[menu.main]]
        identifier = "contact"
        name = "Tags"
        url = "/tags/"
        weight = 10
[params]
    # color style
    color = 'linen'                   # linen, wheat, gray, light
    # header social icons
    github = 'fancive'         # github.com/YOUR_GITHUB_ID
    name = 'fancivez'
    bio = 'golang fan'
    avatar = 'fancivez@gmail.com'         # Gravatar email or image url
    description = "欢迎来到荷兰"
    siteLogoImage = "images/globe.svg"     # shown besides logoTitle
    headerImage = "images/background.jpg"
    logoTitle = "home" # shown on top-left, default: title
    dateFormatToUse = "2006-01-02"
    background_color_class = "bg-black"

[params.giscus]
    data_repo="fancive/blog_discussion"
    data_repo_id="R_kgDOIwDUDQ"
    data_category="Announcements"
    data_category_id="DIC_kwDOIwDUDc4CTgRN"
    data_mapping="pathname"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_theme="preferred_color_scheme"
    data_lang="zh-CN"
    crossorigin="anonymous"

