baseURL = 'https://fancive.github.io/'
languageCode = "zh-cn"
title = '我的博客'
theme = 'PaperMod'
publishDir = "docs"
enableRobotsTXT = true
googleAnalytics = "G-7N49ZFJ61J"

[pagination]
pagerSize = 10

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[menu]
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 5
[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 10
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 15
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 20
[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 25

[params]
author = "fancive"
description = "欢迎来到荷兰"
env = "production"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowWordCount = false
ShowToc = true
TocOpen = false

  [params.homeInfoParams]
  Title = "Hi there"
  Content = "golang fan | 欢迎来到荷兰"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/fancive"

  [[params.socialIcons]]
  name = "email"
  url = "mailto:fancivez@email.com"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = "monokai"
  [markup.goldmark.renderer]
    unsafe = true
