DefaultContentLanguage = "en"

SectionPagesMenu = "main" 
baseURL = 'https://fancive.github.io/' 
disqusShortname = "fancive-github-com" 
enableRobotsTXT = true # generate robots.txt
googleAnalytics = "G-7N49ZFJ61J" 
languageCode = "zh-cn" 
preserveTaxonomyNames = true 
publishDir = "docs" 
show_reading_time = true 
theme = 'dream' 
title = '我的博客' 

[pagination]
pagerSize = 10

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[languages]
[languages.en]
title = "home"
weight = 1

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[menu]
[[menu.main]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 10
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 10
[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 10

[params]
# Dream theme 基本配置
background = "#f7f7f7"
backgroundImage = ""
color = 'linen'
linkColor = "seagreen"

# 个人信息配置
author = "fancive"
avatar = "/images/profile.jpg"
bio = 'golang fan'
motto = "欢迎来到荷兰"
name = 'fancivez'

# 社交链接
email = "fancivez@email.com"
github = "fancive"

# 文章配置
dateFormatToUse = "2006-01-02"
description = "欢迎来到荷兰"
showSummaryCoverInPost = true
summaryLength = 100
truncate = true

# 暗色模式
dark404 = true
darkNav = true

# 其他功能开关
background_color_class = "bg-black"
env = 'production'
headerBottomText = ""
headerImage = "images/background.jpg"
logoTitle = "home"
siteLogoImage = "images/globe.svg"

# i18n
contentType = "posts"
defaultTheme = "light"

# Giscus 评论系统配置
[params.giscus]
crossorigin = "anonymous"
data_category = "Announcements"
data_category_id = "DIC_kwDOIwDUDc4CTgRN"
data_emit_metadata = "0"
data_lang = "zh-CN"
data_mapping = "pathname"
data_reactions_enabled = "1"
data_repo = "fancive/blog_discussion"
data_repo_id = "R_kgDOIwDUDQ"
data_theme = "preferred_color_scheme"
