baseURL = 'https://fancive.github.io/'
languageCode = "en"
DefaultContentLanguage = "en"
title = ''
theme = "den"
publishDir = "docs"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"


[languages]
    [languages.en]
        weight = 1
    [languages.fr]
        weight = 2

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"


[menu]
    [[menu.main]]
        identifier = "categories"
        name = "categories"
        url = "/categories/"
        weight = 10
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 10
    [[menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = 10

[params]
    # color style
    color = 'linen'                   # linen, wheat, gray, light

    # header social icons
    github = 'fancive'         # github.com/YOUR_GITHUB_ID
    name = 'fancivez'
    bio = 'golang fan'
    avatar = 'fancivez@gmail.com'         # Gravatar email or image url
    description = "欢迎来到荷兰"
    siteLogoImage = "images/globe.svg"     # shown besides logoTitle
    headerImage = "images/background.jpg"
    logoTitle = "home" # shown on top-left, default: title
    dateFormatToUse = "2006-01-02"